/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as BackupRouteImport } from './routes/backup'
import { Route as BiometricRouteImport } from './routes/biometric'
import { Route as CategoriesRouteImport } from './routes/categories'
import { Route as ChangePinRouteImport } from './routes/change-pin'
import { Route as FavoritesRouteImport } from './routes/favorites'
import { Route as HomeRouteImport } from './routes/home'
import { Route as LockRouteImport } from './routes/lock'
import { Route as NotesRouteImport } from './routes/notes'
import { Route as PremiumRouteImport } from './routes/premium'
import { Route as SearchRouteImport } from './routes/search'
import { Route as SecurityRouteImport } from './routes/security'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as SetupRouteImport } from './routes/setup'
import { Route as TrashRouteImport } from './routes/trash'
import { Route as NoteIdRouteImport } from './routes/note.$id'
import { Route as NoteNewRouteImport } from './routes/note.new'
import { Route as NoteIdEditRouteImport } from './routes/note.$id.edit'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const BackupRoute = BackupRouteImport.update({
  id: '/backup',
  path: '/backup',
  getParentRoute: () => rootRouteImport,
} as any)
const BiometricRoute = BiometricRouteImport.update({
  id: '/biometric',
  path: '/biometric',
  getParentRoute: () => rootRouteImport,
} as any)
const CategoriesRoute = CategoriesRouteImport.update({
  id: '/categories',
  path: '/categories',
  getParentRoute: () => rootRouteImport,
} as any)
const ChangePinRoute = ChangePinRouteImport.update({
  id: '/change-pin',
  path: '/change-pin',
  getParentRoute: () => rootRouteImport,
} as any)
const FavoritesRoute = FavoritesRouteImport.update({
  id: '/favorites',
  path: '/favorites',
  getParentRoute: () => rootRouteImport,
} as any)
const HomeRoute = HomeRouteImport.update({
  id: '/home',
  path: '/home',
  getParentRoute: () => rootRouteImport,
} as any)
const LockRoute = LockRouteImport.update({
  id: '/lock',
  path: '/lock',
  getParentRoute: () => rootRouteImport,
} as any)
const NotesRoute = NotesRouteImport.update({
  id: '/notes',
  path: '/notes',
  getParentRoute: () => rootRouteImport,
} as any)
const PremiumRoute = PremiumRouteImport.update({
  id: '/premium',
  path: '/premium',
  getParentRoute: () => rootRouteImport,
} as any)
const SearchRoute = SearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => rootRouteImport,
} as any)
const SecurityRoute = SecurityRouteImport.update({
  id: '/security',
  path: '/security',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const SetupRoute = SetupRouteImport.update({
  id: '/setup',
  path: '/setup',
  getParentRoute: () => rootRouteImport,
} as any)
const TrashRoute = TrashRouteImport.update({
  id: '/trash',
  path: '/trash',
  getParentRoute: () => rootRouteImport,
} as any)
const NoteIdRoute = NoteIdRouteImport.update({
  id: '/note/$id',
  path: '/note/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const NoteNewRoute = NoteNewRouteImport.update({
  id: '/note/new',
  path: '/note/new',
  getParentRoute: () => rootRouteImport,
} as any)
const NoteIdEditRoute = NoteIdEditRouteImport.update({
  id: '/edit',
  path: '/edit',
  getParentRoute: () => NoteIdRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/backup': typeof BackupRoute
  '/biometric': typeof BiometricRoute
  '/categories': typeof CategoriesRoute
  '/change-pin': typeof ChangePinRoute
  '/favorites': typeof FavoritesRoute
  '/home': typeof HomeRoute
  '/lock': typeof LockRoute
  '/notes': typeof NotesRoute
  '/premium': typeof PremiumRoute
  '/search': typeof SearchRoute
  '/security': typeof SecurityRoute
  '/settings': typeof SettingsRoute
  '/setup': typeof SetupRoute
  '/trash': typeof TrashRoute
  '/note/$id': typeof NoteIdRouteWithChildren
  '/note/new': typeof NoteNewRoute
  '/note/$id/edit': typeof NoteIdEditRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/backup': typeof BackupRoute
  '/biometric': typeof BiometricRoute
  '/categories': typeof CategoriesRoute
  '/change-pin': typeof ChangePinRoute
  '/favorites': typeof FavoritesRoute
  '/home': typeof HomeRoute
  '/lock': typeof LockRoute
  '/notes': typeof NotesRoute
  '/premium': typeof PremiumRoute
  '/search': typeof SearchRoute
  '/security': typeof SecurityRoute
  '/settings': typeof SettingsRoute
  '/setup': typeof SetupRoute
  '/trash': typeof TrashRoute
  '/note/$id': typeof NoteIdRouteWithChildren
  '/note/new': typeof NoteNewRoute
  '/note/$id/edit': typeof NoteIdEditRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/backup': typeof BackupRoute
  '/biometric': typeof BiometricRoute
  '/categories': typeof CategoriesRoute
  '/change-pin': typeof ChangePinRoute
  '/favorites': typeof FavoritesRoute
  '/home': typeof HomeRoute
  '/lock': typeof LockRoute
  '/notes': typeof NotesRoute
  '/premium': typeof PremiumRoute
  '/search': typeof SearchRoute
  '/security': typeof SecurityRoute
  '/settings': typeof SettingsRoute
  '/setup': typeof SetupRoute
  '/trash': typeof TrashRoute
  '/note/$id': typeof NoteIdRouteWithChildren
  '/note/new': typeof NoteNewRoute
  '/note/$id/edit': typeof NoteIdEditRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/backup'
    | '/biometric'
    | '/categories'
    | '/change-pin'
    | '/favorites'
    | '/home'
    | '/lock'
    | '/notes'
    | '/premium'
    | '/search'
    | '/security'
    | '/settings'
    | '/setup'
    | '/trash'
    | '/note/$id'
    | '/note/new'
    | '/note/$id/edit'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/backup'
    | '/biometric'
    | '/categories'
    | '/change-pin'
    | '/favorites'
    | '/home'
    | '/lock'
    | '/notes'
    | '/premium'
    | '/search'
    | '/security'
    | '/settings'
    | '/setup'
    | '/trash'
    | '/note/$id'
    | '/note/new'
    | '/note/$id/edit'
  id:
    | '__root__'
    | '/'
    | '/backup'
    | '/biometric'
    | '/categories'
    | '/change-pin'
    | '/favorites'
    | '/home'
    | '/lock'
    | '/notes'
    | '/premium'
    | '/search'
    | '/security'
    | '/settings'
    | '/setup'
    | '/trash'
    | '/note/$id'
    | '/note/new'
    | '/note/$id/edit'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BackupRoute: typeof BackupRoute
  BiometricRoute: typeof BiometricRoute
  CategoriesRoute: typeof CategoriesRoute
  ChangePinRoute: typeof ChangePinRoute
  FavoritesRoute: typeof FavoritesRoute
  HomeRoute: typeof HomeRoute
  LockRoute: typeof LockRoute
  NotesRoute: typeof NotesRoute
  PremiumRoute: typeof PremiumRoute
  SearchRoute: typeof SearchRoute
  SecurityRoute: typeof SecurityRoute
  SettingsRoute: typeof SettingsRoute
  SetupRoute: typeof SetupRoute
  TrashRoute: typeof TrashRoute
  NoteIdRoute: typeof NoteIdRouteWithChildren
  NoteNewRoute: typeof NoteNewRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/backup': {
      id: '/backup'
      path: '/backup'
      fullPath: '/backup'
      preLoaderRoute: typeof BackupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/biometric': {
      id: '/biometric'
      path: '/biometric'
      fullPath: '/biometric'
      preLoaderRoute: typeof BiometricRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/categories': {
      id: '/categories'
      path: '/categories'
      fullPath: '/categories'
      preLoaderRoute: typeof CategoriesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/change-pin': {
      id: '/change-pin'
      path: '/change-pin'
      fullPath: '/change-pin'
      preLoaderRoute: typeof ChangePinRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/favorites': {
      id: '/favorites'
      path: '/favorites'
      fullPath: '/favorites'
      preLoaderRoute: typeof FavoritesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/home': {
      id: '/home'
      path: '/home'
      fullPath: '/home'
      preLoaderRoute: typeof HomeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lock': {
      id: '/lock'
      path: '/lock'
      fullPath: '/lock'
      preLoaderRoute: typeof LockRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/notes': {
      id: '/notes'
      path: '/notes'
      fullPath: '/notes'
      preLoaderRoute: typeof NotesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/premium': {
      id: '/premium'
      path: '/premium'
      fullPath: '/premium'
      preLoaderRoute: typeof PremiumRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/search': {
      id: '/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof SearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/security': {
      id: '/security'
      path: '/security'
      fullPath: '/security'
      preLoaderRoute: typeof SecurityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/setup': {
      id: '/setup'
      path: '/setup'
      fullPath: '/setup'
      preLoaderRoute: typeof SetupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/trash': {
      id: '/trash'
      path: '/trash'
      fullPath: '/trash'
      preLoaderRoute: typeof TrashRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/note/$id': {
      id: '/note/$id'
      path: '/note/$id'
      fullPath: '/note/$id'
      preLoaderRoute: typeof NoteIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/note/new': {
      id: '/note/new'
      path: '/note/new'
      fullPath: '/note/new'
      preLoaderRoute: typeof NoteNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/note/$id/edit': {
      id: '/note/$id/edit'
      path: '/edit'
      fullPath: '/note/$id/edit'
      preLoaderRoute: typeof NoteIdEditRouteImport
      parentRoute: typeof NoteIdRoute
    }
  }
}

interface NoteIdRouteChildren {
  NoteIdEditRoute: typeof NoteIdEditRoute
}

const NoteIdRouteChildren: NoteIdRouteChildren = {
  NoteIdEditRoute: NoteIdEditRoute,
}

const NoteIdRouteWithChildren =
  NoteIdRoute._addFileChildren(NoteIdRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BackupRoute: BackupRoute,
  BiometricRoute: BiometricRoute,
  CategoriesRoute: CategoriesRoute,
  ChangePinRoute: ChangePinRoute,
  FavoritesRoute: FavoritesRoute,
  HomeRoute: HomeRoute,
  LockRoute: LockRoute,
  NotesRoute: NotesRoute,
  PremiumRoute: PremiumRoute,
  SearchRoute: SearchRoute,
  SecurityRoute: SecurityRoute,
  SettingsRoute: SettingsRoute,
  SetupRoute: SetupRoute,
  TrashRoute: TrashRoute,
  NoteIdRoute: NoteIdRouteWithChildren,
  NoteNewRoute: NoteNewRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
